<?php
/**
 * EventTargetFilter
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fleet API Specification
 *
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * OpenAPI spec version: 2.83.0
 * Contact: support@keytelematics.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * EventTargetFilter Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EventTargetFilter implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'EventTargetFilter';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'target_type' => 'string',
        'target_type_id' => 'string',
        'target_type_name' => 'string',
        'target_selection_type' => 'string',
        'target_id' => 'string',
        'target_name' => 'string',
        'text' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'target_type' => null,
        'target_type_id' => null,
        'target_type_name' => null,
        'target_selection_type' => null,
        'target_id' => null,
        'target_name' => null,
        'text' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'target_type' => 'targetType',
        'target_type_id' => 'targetTypeId',
        'target_type_name' => 'targetTypeName',
        'target_selection_type' => 'targetSelectionType',
        'target_id' => 'targetId',
        'target_name' => 'targetName',
        'text' => 'text'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'target_type' => 'setTargetType',
        'target_type_id' => 'setTargetTypeId',
        'target_type_name' => 'setTargetTypeName',
        'target_selection_type' => 'setTargetSelectionType',
        'target_id' => 'setTargetId',
        'target_name' => 'setTargetName',
        'text' => 'setText'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'target_type' => 'getTargetType',
        'target_type_id' => 'getTargetTypeId',
        'target_type_name' => 'getTargetTypeName',
        'target_selection_type' => 'getTargetSelectionType',
        'target_id' => 'getTargetId',
        'target_name' => 'getTargetName',
        'text' => 'getText'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const TARGET_SELECTION_TYPE_ANY = 'any';
    const TARGET_SELECTION_TYPE_GROUP = 'group';
    const TARGET_SELECTION_TYPE_SPECIFIC = 'specific';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTargetSelectionTypeAllowableValues()
    {
        return [
            self::TARGET_SELECTION_TYPE_ANY,
            self::TARGET_SELECTION_TYPE_GROUP,
            self::TARGET_SELECTION_TYPE_SPECIFIC,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['target_type'] = isset($data['target_type']) ? $data['target_type'] : null;
        $this->container['target_type_id'] = isset($data['target_type_id']) ? $data['target_type_id'] : null;
        $this->container['target_type_name'] = isset($data['target_type_name']) ? $data['target_type_name'] : null;
        $this->container['target_selection_type'] = isset($data['target_selection_type']) ? $data['target_selection_type'] : null;
        $this->container['target_id'] = isset($data['target_id']) ? $data['target_id'] : null;
        $this->container['target_name'] = isset($data['target_name']) ? $data['target_name'] : null;
        $this->container['text'] = isset($data['text']) ? $data['text'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['target_selection_type'] === null) {
            $invalidProperties[] = "'target_selection_type' can't be null";
        }
        $allowedValues = $this->getTargetSelectionTypeAllowableValues();
        if (!is_null($this->container['target_selection_type']) && !in_array($this->container['target_selection_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'target_selection_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets target_type
     *
     * @return string
     */
    public function getTargetType()
    {
        return $this->container['target_type'];
    }

    /**
     * Sets target_type
     *
     * @param string $target_type target_type
     *
     * @return $this
     */
    public function setTargetType($target_type)
    {
        $this->container['target_type'] = $target_type;

        return $this;
    }

    /**
     * Gets target_type_id
     *
     * @return string
     */
    public function getTargetTypeId()
    {
        return $this->container['target_type_id'];
    }

    /**
     * Sets target_type_id
     *
     * @param string $target_type_id target_type_id
     *
     * @return $this
     */
    public function setTargetTypeId($target_type_id)
    {
        $this->container['target_type_id'] = $target_type_id;

        return $this;
    }

    /**
     * Gets target_type_name
     *
     * @return string
     */
    public function getTargetTypeName()
    {
        return $this->container['target_type_name'];
    }

    /**
     * Sets target_type_name
     *
     * @param string $target_type_name target_type_name
     *
     * @return $this
     */
    public function setTargetTypeName($target_type_name)
    {
        $this->container['target_type_name'] = $target_type_name;

        return $this;
    }

    /**
     * Gets target_selection_type
     *
     * @return string
     */
    public function getTargetSelectionType()
    {
        return $this->container['target_selection_type'];
    }

    /**
     * Sets target_selection_type
     *
     * @param string $target_selection_type target_selection_type
     *
     * @return $this
     */
    public function setTargetSelectionType($target_selection_type)
    {
        $allowedValues = $this->getTargetSelectionTypeAllowableValues();
        if (!in_array($target_selection_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'target_selection_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['target_selection_type'] = $target_selection_type;

        return $this;
    }

    /**
     * Gets target_id
     *
     * @return string
     */
    public function getTargetId()
    {
        return $this->container['target_id'];
    }

    /**
     * Sets target_id
     *
     * @param string $target_id target_id
     *
     * @return $this
     */
    public function setTargetId($target_id)
    {
        $this->container['target_id'] = $target_id;

        return $this;
    }

    /**
     * Gets target_name
     *
     * @return string
     */
    public function getTargetName()
    {
        return $this->container['target_name'];
    }

    /**
     * Sets target_name
     *
     * @param string $target_name target_name
     *
     * @return $this
     */
    public function setTargetName($target_name)
    {
        $this->container['target_name'] = $target_name;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string $text text
     *
     * @return $this
     */
    public function setText($text)
    {
        $this->container['text'] = $text;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


