<?php
/**
 * StatsEntityOutputOptions
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fleet API Specification
 *
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * OpenAPI spec version: 2.83.0
 * Contact: support@keytelematics.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * StatsEntityOutputOptions Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StatsEntityOutputOptions implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'StatsEntityOutputOptions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'group_level' => 'string',
        'row_level' => 'string',
        'time' => 'string',
        'flip' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'group_level' => null,
        'row_level' => null,
        'time' => null,
        'flip' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'group_level' => 'groupLevel',
        'row_level' => 'rowLevel',
        'time' => 'time',
        'flip' => 'flip'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'group_level' => 'setGroupLevel',
        'row_level' => 'setRowLevel',
        'time' => 'setTime',
        'flip' => 'setFlip'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'group_level' => 'getGroupLevel',
        'row_level' => 'getRowLevel',
        'time' => 'getTime',
        'flip' => 'getFlip'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const GROUP_LEVEL_ALL = 'all';
    const GROUP_LEVEL_TYPE = 'type';
    const GROUP_LEVEL_NAME = 'name';
    const GROUP_LEVEL_COMPANY = 'company';
    const GROUP_LEVEL_USER = 'user';
    const GROUP_LEVEL_DISTRIBUTOR = 'distributor';
    const GROUP_LEVEL_VENDOR = 'vendor';
    const GROUP_LEVEL_CLIENT = 'client';
    const ROW_LEVEL_ALL = 'all';
    const ROW_LEVEL_YEAR = 'year';
    const ROW_LEVEL_MONTH = 'month';
    const ROW_LEVEL_DAY = 'day';
    const ROW_LEVEL_HOUR = 'hour';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getGroupLevelAllowableValues()
    {
        return [
            self::GROUP_LEVEL_ALL,
            self::GROUP_LEVEL_TYPE,
            self::GROUP_LEVEL_NAME,
            self::GROUP_LEVEL_COMPANY,
            self::GROUP_LEVEL_USER,
            self::GROUP_LEVEL_DISTRIBUTOR,
            self::GROUP_LEVEL_VENDOR,
            self::GROUP_LEVEL_CLIENT,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRowLevelAllowableValues()
    {
        return [
            self::ROW_LEVEL_ALL,
            self::ROW_LEVEL_YEAR,
            self::ROW_LEVEL_MONTH,
            self::ROW_LEVEL_DAY,
            self::ROW_LEVEL_HOUR,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['group_level'] = isset($data['group_level']) ? $data['group_level'] : null;
        $this->container['row_level'] = isset($data['row_level']) ? $data['row_level'] : null;
        $this->container['time'] = isset($data['time']) ? $data['time'] : null;
        $this->container['flip'] = isset($data['flip']) ? $data['flip'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['group_level'] === null) {
            $invalidProperties[] = "'group_level' can't be null";
        }
        $allowedValues = $this->getGroupLevelAllowableValues();
        if (!is_null($this->container['group_level']) && !in_array($this->container['group_level'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'group_level', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['row_level'] === null) {
            $invalidProperties[] = "'row_level' can't be null";
        }
        $allowedValues = $this->getRowLevelAllowableValues();
        if (!is_null($this->container['row_level']) && !in_array($this->container['row_level'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'row_level', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['time'] === null) {
            $invalidProperties[] = "'time' can't be null";
        }
        if ($this->container['flip'] === null) {
            $invalidProperties[] = "'flip' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets group_level
     *
     * @return string
     */
    public function getGroupLevel()
    {
        return $this->container['group_level'];
    }

    /**
     * Sets group_level
     *
     * @param string $group_level group_level
     *
     * @return $this
     */
    public function setGroupLevel($group_level)
    {
        $allowedValues = $this->getGroupLevelAllowableValues();
        if (!in_array($group_level, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'group_level', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['group_level'] = $group_level;

        return $this;
    }

    /**
     * Gets row_level
     *
     * @return string
     */
    public function getRowLevel()
    {
        return $this->container['row_level'];
    }

    /**
     * Sets row_level
     *
     * @param string $row_level row_level
     *
     * @return $this
     */
    public function setRowLevel($row_level)
    {
        $allowedValues = $this->getRowLevelAllowableValues();
        if (!in_array($row_level, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'row_level', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['row_level'] = $row_level;

        return $this;
    }

    /**
     * Gets time
     *
     * @return string
     */
    public function getTime()
    {
        return $this->container['time'];
    }

    /**
     * Sets time
     *
     * @param string $time time
     *
     * @return $this
     */
    public function setTime($time)
    {
        $this->container['time'] = $time;

        return $this;
    }

    /**
     * Gets flip
     *
     * @return bool
     */
    public function getFlip()
    {
        return $this->container['flip'];
    }

    /**
     * Sets flip
     *
     * @param bool $flip flip
     *
     * @return $this
     */
    public function setFlip($flip)
    {
        $this->container['flip'] = $flip;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


