<?php
/**
 * AnalyticsBaseReportResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fleet API Specification
 *
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * OpenAPI spec version: 2.83.0
 * Contact: support@keytelematics.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AnalyticsBaseReportResponseTest Class Doc Comment
 *
 * @category    Class
 * @description AnalyticsBaseReportResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AnalyticsBaseReportResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AnalyticsBaseReportResponse"
     */
    public function testAnalyticsBaseReportResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {
    }

    /**
     * Test attribute "client"
     */
    public function testPropertyClient()
    {
    }

    /**
     * Test attribute "task_id"
     */
    public function testPropertyTaskId()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "completion_date"
     */
    public function testPropertyCompletionDate()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "progress"
     */
    public function testPropertyProgress()
    {
    }

    /**
     * Test attribute "completed_tasks"
     */
    public function testPropertyCompletedTasks()
    {
    }

    /**
     * Test attribute "total_tasks"
     */
    public function testPropertyTotalTasks()
    {
    }

    /**
     * Test attribute "first_pass_complete"
     */
    public function testPropertyFirstPassComplete()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "mode"
     */
    public function testPropertyMode()
    {
    }

    /**
     * Test attribute "max_running"
     */
    public function testPropertyMaxRunning()
    {
    }

    /**
     * Test attribute "run_end_date"
     */
    public function testPropertyRunEndDate()
    {
    }

    /**
     * Test attribute "last_completed_date"
     */
    public function testPropertyLastCompletedDate()
    {
    }

    /**
     * Test attribute "dashboards"
     */
    public function testPropertyDashboards()
    {
    }
}
